name: builder
on:
  push:
    branches:
      - main
  # Uncomment the section below to enable scheduled builds
  schedule:
    # Run this script every 2 hr
    #  */m hr day month day_of_week
    - cron:  '0 */2 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'tag'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: run
        run: |
          deno task build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          single-commit: true
          git-config-email: <>
          branch: gh-pages
          folder: output
